[package]
name = "system76_gop_policy"
version = "1.0.0"
edition = "2024"
license = "GPL-3.0-only"

[profile.release]
lto = true

[dependencies]
#redox_uefi_std = "0.1.13"
redox_uefi_std = { git = "https://gitlab.redox-os.org/redox-os/uefi.git", rev = "8115456dad76" }
