name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install --yes make
        rustup show active-toolchain || rustup toolchain install

    - name: Build UEFI application
      run: make
