name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install --yes make
        rustup show

    - name: Build UEFI application
      env:
          FIRMWARE_OPEN_VBT: "../lemp9.vbt"
      run: make
