name: CI
on:
  push:
    branches: [master]
  pull_request:

env:
    FIRMWARE_OPEN_VBT: "../lemp9.vbt"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install --no-install-recommends --assume-yes just rustup
        rustup show

    - name: clippy
      run: just clippy -- -D warnings

    - name: fmt
      run: just fmt --check

    - name: build
      run: just build --release
